package me.itangqi.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.mobi.greendao.entity.Customer;
import com.example.mobi.greendao.entity.Goods;
import com.example.mobi.greendao.entity.Note;
import com.example.mobi.greendao.entity.Order;

import me.itangqi.greendao.CustomerDao;
import me.itangqi.greendao.GoodsDao;
import me.itangqi.greendao.NoteDao;
import me.itangqi.greendao.OrderDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig customerDaoConfig;
    private final DaoConfig goodsDaoConfig;
    private final DaoConfig noteDaoConfig;
    private final DaoConfig orderDaoConfig;

    private final CustomerDao customerDao;
    private final GoodsDao goodsDao;
    private final NoteDao noteDao;
    private final OrderDao orderDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        customerDaoConfig = daoConfigMap.get(CustomerDao.class).clone();
        customerDaoConfig.initIdentityScope(type);

        goodsDaoConfig = daoConfigMap.get(GoodsDao.class).clone();
        goodsDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        customerDao = new CustomerDao(customerDaoConfig, this);
        goodsDao = new GoodsDao(goodsDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);
        orderDao = new OrderDao(orderDaoConfig, this);

        registerDao(Customer.class, customerDao);
        registerDao(Goods.class, goodsDao);
        registerDao(Note.class, noteDao);
        registerDao(Order.class, orderDao);
    }
    
    public void clear() {
        customerDaoConfig.getIdentityScope().clear();
        goodsDaoConfig.getIdentityScope().clear();
        noteDaoConfig.getIdentityScope().clear();
        orderDaoConfig.getIdentityScope().clear();
    }

    public CustomerDao getCustomerDao() {
        return customerDao;
    }

    public GoodsDao getGoodsDao() {
        return goodsDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

}
